variables:
  ARTIFACT_NAME: accounting-api-1.0.$CI_PIPELINE_IID.jar

stages:
  - test
  - build
  - functional tests
  - deploy

unit tests:
  stage: test
  image: openjdk:12-alpine
  script:
    - ./mvnw test -DskipITs=true

build a jar:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./mvnw package -Dmaven.test.skip=true
    - mkdir ./build
    - mv target/accounting-api-1.0.0.jar ./build/$ARTIFACT_NAME
  artifacts:
    paths:
      - ./build

integration tests:
  stage: functional tests
  image: openjdk:12-alpine
  script:
    - java -jar -Dspring.profiles.active=dev ./build/$ARTIFACT_NAME &
    - sleep 40
    - ./mvnw verify -DskipUTs=true

postman tests:
  stage: functional tests
  image: alexvaitsekhovich/alpine-jre-newman
  script:
    - java -jar -Dspring.profiles.active=dev ./build/$ARTIFACT_NAME &
    - sleep 40
    - newman run src/main/resources/testing_data/functional_testing.postman_collection.json
  dependencies:
    - build a jar

push to docker:
  stage: deploy
  image: openjdk:12-alpine
  script:
    - ./mvnw clean compile jib:build -Djib.to.auth.username=alexvaitsekhovich -Djib.to.auth.password="${DOCKERHUB_PASSWORD}"
  dependencies:
    - build a jar
  only:
    - main
